# Generated by Django 3.2.5 on 2021-07-16 15:40

from django.db import migrations, models
import image_cropping.fields
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(help_text='This will be the text that gets displayed')),
                ('image', models.ImageField(upload_to='template_photos')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': ' About Us Page Entries',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=64)),
                ('location', models.CharField(help_text='Event address ex: 3355 Dalrymple Dr, Baton Rouge, LA 70802', max_length=64)),
                ('date', models.DateField(blank=True, help_text='Select a date from the picker.', null=True)),
                ('time', models.CharField(help_text='Example: 3pm - 5pm', max_length=64)),
                ('public', models.BooleanField(default=False, help_text='When this is checked the event will be displayed on the website')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(help_text='This will be the text that gets displayed')),
                ('image', models.ImageField(upload_to='template_photos')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': ' Home Page Entries',
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('staff', models.CharField(choices=[('Officer', 'Officer'), ('Coach', 'Coach')], default='Officer', max_length=64)),
                ('picture', models.ImageField(upload_to='leadership')),
                ('writeUp', models.TextField(help_text='This will be the text that get displayed under the officer')),
                ('my_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
        migrations.CreateModel(
            name='PageBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('home_page_title', models.CharField(default='Welcome To LSU Rowing', max_length=50)),
                ('home_Banner', models.ImageField(default='', upload_to='banners')),
                ('recruitment_page_title', models.CharField(max_length=50)),
                ('recruitment_Banner', models.ImageField(upload_to='banners')),
                ('about_page_title', models.CharField(max_length=50)),
                ('about_Banner', models.ImageField(upload_to='banners')),
                ('schedule_page_title', models.CharField(max_length=50)),
                ('schedule_Banner', models.ImageField(upload_to='banners')),
                ('sponsor_page_title', models.CharField(max_length=50)),
                ('sponsor_Banner', models.ImageField(upload_to='banners')),
            ],
            options={
                'verbose_name_plural': '     Page Banners',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asociated_event', models.CharField(default='Picture', help_text='Source of the event', max_length=64)),
                ('description', models.CharField(default='Picture', help_text='Describe your images so they can easily be identified to be added into appropriate gallery ', max_length=64)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(help_text='Event address ex: 3355 Dalrymple Dr, Baton Rouge, LA 70802', max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=64)),
                ('public', models.BooleanField(default=False, help_text='When this is checked the race will be displayed on the website')),
                ('results', models.TextField(blank=True, help_text='List Event Results Here', null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(help_text='This will be the text that gets displayed')),
                ('questionaire_link', models.CharField(max_length=128)),
                ('image', models.ImageField(default='none', help_text='This will be the image that gets displayed under the text', upload_to='recruitmentPagePictures')),
            ],
            options={
                'verbose_name_plural': ' Recruitment Page Entries',
            },
        ),
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('orientation', models.CharField(choices=[('Starboard', 'Starboard'), ('Port', 'Port'), ('Bisweptual', 'Bisweptual'), ('Coxswain', 'Coxswain')], max_length=64)),
                ('hometown', models.CharField(help_text='Example: Baton Rouge, LA', max_length=64)),
                ('major', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='')),
                ('cropping', image_cropping.fields.ImageRatioField('picture', '5x7', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('crew', models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens')], max_length=64)),
                ('varsity', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=64)),
                ('year', models.CharField(choices=[('Freshmen', 'FR'), ('Sophomore', 'SO'), ('Junior', 'JR'), ('Senior', 'SR')], max_length=64)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='SponsorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('text', models.TextField(help_text='This will be the text that gets displayed')),
                ('sponsorship_coordinator_name', models.CharField(max_length=64)),
                ('sponsorship_coordinator_email', models.EmailField(help_text='Refer to LSU email', max_length=254)),
                ('image', models.ImageField(upload_to='template_photos')),
            ],
            options={
                'verbose_name_plural': ' Sponsor Page Entries',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name for the gallery', max_length=64)),
                ('date', models.DateField(help_text='Date the event occured')),
                ('full_gallery_link', models.URLField(blank=True, default='', help_text='place google drive url here for the whole album')),
                ('images', sortedm2m.fields.SortedManyToManyField(help_text=None, to='rowingWebsiteApp.Picture')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['-date'],
            },
        ),
    ]
